<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <RootNamespace>PennyPet</RootNamespace>
    <AssemblyName>PennyPet.App</AssemblyName>
    <StartupObject>PennyPet.PennyAppProgram</StartupObject>
    <ApplicationManifest>$(PennyGeneratedManifest)</ApplicationManifest>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Platforms>AnyCPU;x86;x64</Platforms>
    <PlatformTarget Condition="'$(PlatformTarget)' == ''">AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PennyPet.AppProgram.cs" />
    <ProjectReference Include="PennyPet.Windows.Core.csproj" />
  </ItemGroup>
</Project>
